name: Defect report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Что случилось?
      description: Опишите пролему.
      placeholder: Опишите здесь!
    validations: 
      required: true
  - type: textarea
    id: placement
    attributes:
      label: Шаги воспроизведения
      description: Расскажите, что вы сделали для обнаружения ошибки?
      placeholder: Описание действий.
    validations:
      required: false
  - type: textarea
    id: suggestions
    attributes:
      label: Решение проблемы. 
      description: Предложите свой вариант решения проблемы.
      placeholder: Вариант решения.
    validations:
      required: false
    - type: photo
    id: suggestions
    attributes:
      label: Решение проблемы. 
      description: Предложите свой вариант решения проблемы.
      placeholder: Вариант решения.
    validations:
      required: false
  - type: dropdown
    id: seriousness
    attributes:
      label: Seriousness
      description: How serious is the problem?
      options:
        - Blocker
        - Critical
        - Major
        - Trivial
        - Enhancement
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: In what order should the bugs be fixed? 
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: dropdown
    id: bug-type
    attributes:
      label: BugType
      description: What category does the problem belong to?
      options:
        - Functional
        - UI
        - Localization
        - Performance
        - Security
        - Other
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our terms.
      options:
        - label: I agree to follow this project's Code of Conduct
