name: Defect report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Описание дефекта
      description: описание
      placeholder: подсказка
    validations:
      required: true #поле обязательно для заполнения
