name: Defect report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Что случилось?
      description: Опишите пролему.
      placeholder: Опишите здесь!
    validations: 
      required: true
  - type: textarea
    id: placement
    attributes:
      label: Шаги воспроизведения
      description: Расскажите, что вы сделали для обнаружения ошибки?
      placeholder: Описание действий.
    validations:
      required: false
  - type: textarea
    id: suggestions
    attributes:
      label: Решение проблемы
      description: Предложите свой вариант решения проблемы.
      placeholder: Вариант решения.
    validations:
      required: false
  - type: dropdown
    id: seriousness
    attributes:
      label: Серьёзность
      description: Насколько серьёзна проблема?
      options:
        - Критическая
        - Высокая
        - Средняя
        - Низкая
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Приоритет
      description: Какой приоритет имеет ошибка?
      options:
        - Высокий
        - Средний
        - Низкий
    validations:
      required: true
  - type: dropdown
    id: bug-type
    attributes:
      label: Тип ошибки
      description: К какой категории относится ошибка?
      options:
        - Функциональная
        - Пользовательский интерфейс
        - Локализации
        - Производительности
        - Безопасности
        - Другие
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Условия соглашения
      description: Отправляя этот вопрос, вы соглашаетесь следовать нашим условиям.
      options:
        - label: Я согласен следовать условиям этого проекта.
